save_bins: false
seq_lengths: [128, 512, 1024, 4096]
embed_dims: [128, 2048, 4096, 8192]
num_attn_heads: [1, 4, 8, 16]
batch_sizes: [1]
runs_per_benchmark: 5
benchmarks_to_run:
- "vanilla"
- "vanilla_v2"
- "vanilla_cublas"

# save_bins: true
# seq_lengths: [4096]
# embed_dims: [8192]
# num_attn_heads: [4]
# batch_sizes: [1]
# runs_per_benchmark: 1
# benchmarks_to_run:
# - "vanilla_v2"